# PlatformIO Project Configuration File

[env]
platform = ststm32@20.0.0
board = nucleo_c031c6
framework = stm32cube

# must override these settings cuz the `board` template may be different from the actual mcu
board_build.mcu = stm32c011f4p6
board_build.f_cpu = 48000000L
board_build.flash_size = 16k
board_build.rom_start = 0x08000000
board_build.ram_size = 6k

upload_protocol = stlink
debug_tool = stlink

# all build envs use these
extra_scripts =
    scripts/run_formatter.py # adds format custom targets

# customize source file inclusion/exclusion
build_src_filter =
    # start by including everything
    +<*> -<.git/> -<.svn/>
    # same for rocketlib
    -<third_party/rocketlib/**>
    +<third_party/rocketlib/common/**>

# build settings common to all build types
build_flags = 
	-DSTM32C011xx
    -mfloat-abi=soft
    -Iinc
    -Isrc/third_party/rocketlib/include
    -Isrc/third_party

# build settings unique to release build (full optimization, etc)
[env:release]
build_flags =
    ${env.build_flags}

# build for debugger
[env:debug]
build_type = debug

build_flags =
    ${env.build_flags}
    -DDEBUG
    -Og
    -g3
